name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Build
        run: go build -o ./build/phpvm.exe ./cmd/

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: phpvm
          path: ./build/phpvm.exe

      - name: Create Release
        uses: Actions-R-Us/actions-tagger@95c51c646e75db5c6b7d447e3087bcee58677341
        with:
          publish_latest: true
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
